#pragma once

#include <vector>
#include <string>

enum SCRIPT_TYPE
{
	BRIDGESCRIPT,
	CAMERAMOVESCRIPT,
	CINEMATICSCRIPT,
	ENEMYHITBOXSCRIPT,
	ENTETELEVATORSCRIPT,
	EVILPUMPKINSCRIPT,
	EXITELEVATORSCRIPT,
	FLYINGBOOKSCRIPT,
	GAMEMANAGERSCRIPT,
	GHOSTSCRIPT,
	HALLOFETERNITY_FLOOR1_CINEMATICSCRIPT,
	LEVELCHANGESCRIPT,
	PLAYBUTTONSCRIPT,
	PLAYERCAMERASCRIPT,
	PLAYERDETECTSCRIPT,
	PLAYERHITBOXSCRIPT,
	PLAYERLIFEBARSCRIPT,
	PLAYERMANABARSCRIPT,
	PLAYERSCRIPT,
	PROJECTILE2DSCRIPT,
	PYROGHOSTSCRIPT,
	SKELETONHANDSCRIPT,
	SPOOKSMENSCRIPT,
	END,
};

using namespace std;

class CScript;

class CScriptMgr
{
public:
	static void GetScriptInfo(vector<wstring>& _vec);
	static CScript* GetScript(const wstring& _strScriptName);
	static CScript* GetScript(UINT _iScriptType);
	static const wchar_t* GetScriptName(CScript* _pScript);
};
